##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-ingress-gateway
  namespace: com-gft-deuba-unity-release-1
  labels: 
    PROJECT: com.gft.deuba.unity.release-1

spec:

  selector:
    istio: ingressgateway

  servers:

  - port:
      number: 80
      name: http
      protocol: HTTP

    hosts:

    - "*"

##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
  namespace: com-gft-deuba-unity-release-1
  labels:
    PROJECT: com.gft.deuba.unity.release-1
    app: frontend

spec:

  hosts:

    - "*"

  gateways:

    - app-ingress-gateway

  http:

# ----------------------------------------------------------------------------

    - name: thermometer

      match:

      - uri:
          prefix: /thermometer/

      rewrite:
        uri: /

      route:
        - destination:
            host: thermometer

    - name: frontend

      route:
        - destination:
            host: frontend
            port:
              number: 80

