##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: random-destination
  namespace: com-gft-deuba-unity-release-1
  labels:
    PROJECT: com.gft.deuba.unity.release-1
    app: random

spec:

  host: random
  
  subsets:

  - name: prod
    labels:
      version: "1.0.0"

  - name: pre-prod
    labels:
      version: "2.0.0"
