##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress-pre-prod
  namespace: com-gft-deuba-unity-release-1
  labels:
    PROJECT: com.gft.deuba.unity.release-1
    app: frontend

spec:

  hosts:

    - "mysite-uat.localgft.com"

  gateways:

    - app-ingress-gateway

  http:

# ----------------------------------------------------------------------------

    - name: frontend-pre-prod

      headers:

        request:
          set:
            x-environment: pre-prod

        response:
          set:
            x-environment: pre-prod

      route:
        - destination:
            host: frontend
            port:
              number: 80

##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress-prod
  namespace: com-gft-deuba-unity-release-1
  labels:
    PROJECT: com.gft.deuba.unity.release-1
    app: frontend

spec:

  hosts:

    - "mysite-prod.localgft.com"

  gateways:

    - app-ingress-gateway

  http:

# ----------------------------------------------------------------------------

    - name: frontend-prod

      headers:

        request:
          set:
            x-environment: prod

        response:
          set:
            x-environment: prod

      route:
        - destination:
            host: frontend
            port:
              number: 80

