##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: random-ingress-api
  namespace: com-gft-deuba-unity-release-1
  labels:
    PROJECT: com.gft.deuba.unity.release-1
    app: random
    version: "1.0.0"

spec:

  hosts:

    - "mysite-dev.localgft.com"

  gateways:

    - app-ingress-gateway

  http:

# ----------------------------------------------------------------------------

    - name: random-pre-prod

      match:

      - uri:
          prefix: /random/

        headers:
          origin:
            regex: .*mysite-uat.localgft.com.*

      - uri:
          prefix: /random/

        headers:
          x-environment: 
            exact: pre-prod

      rewrite:
        uri: /

      headers:
        request:
          set:
            x-environment: pre-prod

        response:
          set:
            x-environment: pre-prod

      route:
        - destination:
            host: random
            subset: pre-prod

# ----------------------------------------------------------------------------

    - name: random-prod

      match:

      - uri:
          prefix: /random/

        headers:
          origin:
            regex: .*mysite-prod.localgft.com.*

      - uri:
          prefix: /random/

        headers:
          x-environment: 
            exact: prod

      rewrite:
        uri: /

      headers:
        request:
          set:
            x-environment: prod

        response:
          set:
            x-environment: prod

      route:
        - destination:
            host: random
            subset: prod

##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: random-int-api
  namespace: com-gft-deuba-unity-release-1
  labels:
    PROJECT: com.gft.deuba.unity.release-1
    app: random
    version: "1.0.0"

spec:

  hosts:

    - "random"

  http:

# ----------------------------------------------------------------------------

    - name: random-pre-prod

      match:

      - headers:
          origin:
            regex: .*mysite-uat.localgft.com.*

      - headers:
          x-environment: 
            exact: pre-prod

      rewrite:
        uri: /

      headers:
        request:
          set:
            x-environment: pre-prod

      route:
        - destination:
            host: random
            subset: pre-prod

# ----------------------------------------------------------------------------

    - name: random-prod

      match:

      - headers:
          origin:
            regex: .*mysite-prod.localgft.com.*

      - headers:
          x-environment: 
            exact: prod

      rewrite:
        uri: /

      headers:
        request:
          set:
            x-environment: prod

      route:
        - destination:
            host: random
            subset: prod
